import MyTable from "@/components/table/MyTable";
import MyTag from "@/components/tag/MyTag";

export default function BillsToPaySearch() {
  return (
    <MyTable
      columns={[
        { key: "cod", label: "Código", style: { width: "10px" } },
        { key: "type", label: "Tipo" },
        { key: "customer", label: "Cliente" },
        { key: "creation-date", label: "Data de emissão" },
        { key: "previous-date", label: "Data prevista" },
        { key: "price-value", label: "Valor" },
        { key: "amount-paid", label: "Valor pago" },
        { key: "balance-value", label: "Valor restante" },
        { key: "annotation", label: "Anotação" },
      ]}
      datasource={[
        [
          { text: "1" },
          { text: <MyTag color="red">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="blue">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
        [
          { text: "1" },
          { text: <MyTag color="green">Agropet</MyTag> },
          { text: "Consumidor" },
          { text: "20/04/2024" },
          { text: "28/04/2024" },
          { text: "1500,98" },
          { text: "1000,00" },
          { text: "500,98" },
          {
            text: "Aqui eu vou definir uma anotação bem daora pra por no meu projetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojetoprojeto",
            style: {
              maxWidth: "300px",
              overflow: "hidden",
              textOverflow: "ellipsis",
            },
          },
        ],
      ]}
    />
  );
}
